name: GitHub Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Eslint und Stylelint installieren
        run: cd FrontEnd
          npm install eslint --save-dev

      - name: Abhängigkeiten installieren
        run: npm ci

      - name: ESLint ausführen
        run: cd FrontEnd && npm run lint

      - name: Prettier ausführen
        run: cd FrontEnd && npm run prettier

      - name: build
        run: cd FrontEnd && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./FrontEnd/dist
          publish_branch: gh-pages
          force_orphan: true
          commit_message: "Deploy to GitHub Pages"
          user_name: "ErwinHlz"
          user_email: "erwinholzhauser.eh@gmail.com"
