name: GitHub Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Eslint und Stylelint installieren
        run: |
          cd FrontEnd
          npm install eslint --save-dev

      - name: Abhängigkeiten installieren
        run: npm ci

      - name: ESLint ausführen
        run: cd FrontEnd && npm run lint

      - name: Prettier ausführen
        run: cd FrontEnd && npm run prettier
